name = "warp3"
main = "src/index.ts"
compatibility_date = "2023-08-23"

[[d1_databases]]
binding = "DATABASE"
database_name = "warp-db"
database_id = "1adf4fe3-f896-4718-8c65-8584f6f19b26"

[triggers]
crons = [
    '* * * * *', # every minute
]

